version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER: "postgres"
      - POSTGRES_PASSWORD: "postgres"
      - POSTGRES_DB: "mas"
    ports:
      - "5432:5432"
    volumes:
      - /home/Development/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge